spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/store
    username: store-user
    password: store-pass
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
