spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/vehicle
    username: vehicle-user
    password: vehicle-pass
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
