spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dealer
    username: dealer-user
    password: dealer-pass
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
